<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4740962499ab78e2cf977976d8718b79
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LZCompressor\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LZCompressor\\' => 
        array (
            0 => __DIR__ . '/..' . '/nullpunkt/lz-string-php/src/LZCompressor',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4740962499ab78e2cf977976d8718b79::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4740962499ab78e2cf977976d8718b79::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4740962499ab78e2cf977976d8718b79::$classMap;

        }, null, ClassLoader::class);
    }
}
